
### Read all movies
@baseUrl = http://localhost:3000
GET {{baseUrl}}/movies

### Read all filtered
GET {{baseUrl}}/movies/?minimum-duration=200

### Read one
GET {{baseUrl}}/movies/2


### Create one 
POST {{baseUrl}}/movies
Content-Type: application/json

{ 
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "director": "George Lucas",
    "budget": 115,
    "image-url":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}
    



