
### Read all movies
@baseUrl = http://localhost:3000
GET {{baseUrl}}/movies

### Read all filtered
GET {{baseUrl}}/movies/?minimum-duration=200

### Read one
GET {{baseUrl}}/movies/2


### Create one 
POST {{baseUrl}}/movies
Content-Type: application/json

{ 
    
  "title" : "hey",
  "director" : "me",
  "duration" : 200,
  "budget" : 35000,
  "description" : "idk",
  "imageUrl" : null
}
    
### Delete a movie
DELETE {{baseUrl}}/movies/2

### Update the movie identified by 3
PATCH {{baseUrl}}/movies/3
Content-Type: application/json

{

    "title":"Magic Green 2"
}


